//
//  TuneKeyStrings.h
//  Tune
//
//  Created by Pavel Yurchenko on 7/16/12.
//  Copyright (c) 2012 Scopic Software. All rights reserved.
//

FOUNDATION_EXPORT NSString * const TUNE_KEY_ACTION;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_APP_AD_TRACKING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_APP_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_APP_VERSION;
FOUNDATION_EXPORT NSString * const TUNE_KEY_BLUETOOTH_STATE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_BYPASS_THROTTLING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CAMPAIGN_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CONVERSION_USER_AGENT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_COUNTRY_CODE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CURRENCY_CODE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CURRENCY_USD;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DATA;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEBUG;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEEPLINK_CHECKED;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_BRAND;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_CARRIER;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_CPUTYPE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_CPUSUBTYPE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_FORM;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_FORM_WEARABLE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_DEVICE_MODEL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EXISTING_USER;
FOUNDATION_EXPORT NSString * const TUNE_KEY_FACEBOOK_USER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_FB_COOKIE_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_GEOFENCE_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_GOOGLE_USER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_GUID_EMPTY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_HTTPS;
FOUNDATION_EXPORT NSString * const TUNE_KEY_INSDATE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_ATTRIBUTION;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_IMPRESSION_DATE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_CAMPAIGN_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_CAMPAIGN_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_CAMPAIGN_ORG_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_LINE_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_LINE_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_CREATIVE_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IAD_CREATIVE_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_INSTALL_RECEIPT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IOS;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IOS_AD_TRACKING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IOS_IFA;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IOS_IFA_DEEPLINK;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IOS_IFV;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IOS_PURCHASE_STATUS;
FOUNDATION_EXPORT NSString * const TUNE_KEY_IS_PAYING_USER;
FOUNDATION_EXPORT NSString * const TUNE_KEY_JSON;
FOUNDATION_EXPORT NSString * const TUNE_KEY_KEY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LAST_OPEN_LOG_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LANGUAGE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LOCATION_AUTH_STATUS;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LOCATION_HORIZONTAL_ACCURACY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LOCATION_TIMESTAMP;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LOCATION_VERTICAL_ACCURACY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LOG_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_MAT_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ODIN;
FOUNDATION_EXPORT NSString * const TUNE_KEY_OPEN_LOG_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_OPEN_UDID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_OS_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_OS_JAILBROKE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_OS_VERSION;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PACKAGE_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_POST_CONVERSION;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REDIRECT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REDIRECT_URL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REF_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REFERRAL_SOURCE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REFERRAL_URL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REQUEST_URL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_RESPONSE_FORMAT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_RETRY_COUNT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_REVENUE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_RUN_DATE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SCREEN_DENSITY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SCREEN_SIZE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SDK;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SDK_PLUGIN;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SERVER_RESPONSE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SESSION_DATETIME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SITE_EVENT_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SITE_EVENT_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SITE_EVENT_TYPE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SKIP_DUP;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SITE_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_STAGING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_STORE_RECEIPT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SUCCESS;
FOUNDATION_EXPORT NSString * const TUNE_KEY_SYSTEM_DATE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_TARGET_BUNDLE_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_TRACKING_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_TRANSACTION_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_TRUSTE_TPID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_TWITTER_USER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_UPDATE_LOG_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_URL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_EMAIL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_NAME;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_PHONE;

FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_NAME_MD5;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_NAME_SHA1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_NAME_SHA256;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_EMAIL_MD5;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_EMAIL_SHA1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_EMAIL_SHA256;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_PHONE_MD5;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_PHONE_SHA1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_USER_PHONE_SHA256;

FOUNDATION_EXPORT NSString * const TUNE_KEY_VER;
FOUNDATION_EXPORT NSString * const TUNE_KEY_XML;

FOUNDATION_EXPORT NSString * const TUNE_KEY_CWORKS_CLICK;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CWORKS_IMPRESSION;

FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_CONTENT_TYPE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_CONTENT_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_LEVEL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_QUANTITY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_SEARCH_STRING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_RATING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_DATE1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_DATE2;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB2;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB3;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB4;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB5;

FOUNDATION_EXPORT NSString * const TUNE_KEY_ITEM;
FOUNDATION_EXPORT NSString * const TUNE_KEY_QUANTITY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_UNIT_PRICE;

FOUNDATION_EXPORT NSString * const TUNE_KEY_AGE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_GENDER;

FOUNDATION_EXPORT NSString * const TUNE_KEY_LATITUDE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_LONGITUDE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ALTITUDE;

FOUNDATION_EXPORT NSString * const TUNE_KEY_ATTRIBUTE_SUB1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ATTRIBUTE_SUB2;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ATTRIBUTE_SUB3;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ATTRIBUTE_SUB4;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ATTRIBUTE_SUB5;

FOUNDATION_EXPORT NSString * const TUNE_KEY_CARRIER_COUNTRY_CODE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CARRIER_COUNTRY_CODE_ISO;
FOUNDATION_EXPORT NSString * const TUNE_KEY_CARRIER_NETWORK_CODE;

FOUNDATION_EXPORT NSString * const TUNE_DEFAULT_LOCALE_IDENTIFIER;
FOUNDATION_EXPORT NSString * const TUNE_DEFAULT_TIMEZONE;

FOUNDATION_EXPORT NSString * const TUNE_EVENT_INSTALL;
FOUNDATION_EXPORT NSString * const TUNE_EVENT_UPDATE;
FOUNDATION_EXPORT NSString * const TUNE_EVENT_OPEN;
FOUNDATION_EXPORT NSString * const TUNE_EVENT_CLICK;
FOUNDATION_EXPORT NSString * const TUNE_EVENT_CLOSE;
FOUNDATION_EXPORT NSString * const TUNE_EVENT_CONVERSION;
FOUNDATION_EXPORT NSString * const TUNE_EVENT_GEOFENCE;

FOUNDATION_EXPORT NSString * const TUNE_HTTP_METHOD_POST;
FOUNDATION_EXPORT NSString * const TUNE_HTTP_CONTENT_LENGTH;
FOUNDATION_EXPORT NSString * const TUNE_HTTP_CONTENT_TYPE;
FOUNDATION_EXPORT NSString * const TUNE_HTTP_CONTENT_TYPE_APPLICATION_JSON;

FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_DOMAIN;

FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_SERVER_ERROR;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_ADVERTISER_ID_MISSING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_CONVERSION_KEY_MISSING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_CONVERSION_KEY_INVALID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_INVALID_PARAMETERS;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_APP_TO_APP_FAILURE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_NETWORK_NOT_REACHABLE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_OPEN_EVENT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ERROR_TUNE_CLOSE_EVENT;

FOUNDATION_EXPORT NSString * const TUNE_KEY_MAT_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_MAT_INSTALL_LOG_ID_REQUEST_TIMESTAMP;
FOUNDATION_EXPORT NSString * const TUNE_KEY_MAT_UPDATE_LOG_ID;

FOUNDATION_EXPORT NSString * const TUNE_KEY_MAT_FIXED_FOR_ICLOUD;

FOUNDATION_EXPORT NSString * const TUNE_STRING_EMPTY;

FOUNDATION_EXPORT NSString * const TUNE_SERVER_DOMAIN_COOKIE_TRACKING;
FOUNDATION_EXPORT NSString * const TUNE_SERVER_DOMAIN_REGULAR_TRACKING_PROD;
FOUNDATION_EXPORT NSString * const TUNE_SERVER_DOMAIN_REGULAR_TRACKING_PROD_DEBUG;
FOUNDATION_EXPORT NSString * const TUNE_SERVER_DOMAIN_REGULAR_TRACKING_STAGE;
FOUNDATION_EXPORT NSString * const TUNE_SERVER_PATH_TRACKING_ENGINE;

FOUNDATION_EXPORT NSString * const TUNE_SERVER_DOMAIN_DEEPLINK;
FOUNDATION_EXPORT NSString * const TUNE_SERVER_PATH_DEEPLINK;

FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_SUB_AD;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_SUB_ADGROUP;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_SUB_CAMPAIGN;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_SUB_KEYWORD;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_SUB_PUBLISHER;
FOUNDATION_EXPORT NSString * const TUNE_KEY_ADVERTISER_SUB_SITE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_AGENCY_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_OFFER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PRELOAD_DATA;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_REF_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB_AD;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB_ADGROUP;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB_CAMPAIGN;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB_KEYWORD;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB_PUBLISHER;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB_SITE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB2;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB3;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB4;
FOUNDATION_EXPORT NSString * const TUNE_KEY_PUBLISHER_SUB5;
