//
//  TuneEventKeys.h
//  TuneMarketingConsoleSDK
//
//  Created by Charles Gilliam on 8/18/15.
//  Copyright (c) 2015 Tune. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_REVENUE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_CURRENCY_CODE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_REFERENCE_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_RECEIPT;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_TRANSACTION_STATE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_CONTENT_TYPE;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_CONTENT_ID;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_LEVEL;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_QUANTITY;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_SEARCH_STRING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_RATING;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_DATE1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_DATE2;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB1;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB2;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB3;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB4;
FOUNDATION_EXPORT NSString * const TUNE_KEY_EVENT_ATTRIBUTE_SUB5;
