//
//  TuneUserProfileKeys.h
//  TuneMarketingConsoleSDK
//
//  Created by Charles Gilliam on 8/7/15.
//  Copyright (c) 2015 Tune. All rights reserved.
//

FOUNDATION_EXPORT NSString *const TUNE_KEY_SESSION_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SESSION_LAST_DATE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SESSION_CURRENT_DATE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SESSION_COUNT;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IS_FIRST_SESSION;
FOUNDATION_EXPORT NSString *const TUNE_KEY_CUSTOM_VARIABLES;

FOUNDATION_EXPORT NSString *const TUNE_KEY_INSTALL_RECEIPT;

FOUNDATION_EXPORT NSString *const TUNE_KEY_INSDATE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SESSION_DATETIME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SYSTEM_DATE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_REFERRAL_URL;
FOUNDATION_EXPORT NSString *const TUNE_KEY_REFERRAL_SOURCE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_REDIRECT_URL;

FOUNDATION_EXPORT NSString *const TUNE_KEY_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_UPDATE_LOG_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_OPEN_LOG_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_LAST_OPEN_LOG_ID;

FOUNDATION_EXPORT NSString *const TUNE_KEY_CURRENCY_CODE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_OS_JAILBROKE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_TRACKING_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_MAT_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_FB_COOKIE_ID;

FOUNDATION_EXPORT NSString *const TUNE_KEY_IOS_IFV;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IOS_IFA;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IOS_AD_TRACKING;

FOUNDATION_EXPORT NSString *const TUNE_KEY_IAD_ATTRIBUTION;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IAD_IMPRESSION_DATE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IAD_CLICK_DATE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IAD_CONVERSION_DATE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_APP_AD_TRACKING;

FOUNDATION_EXPORT NSString *const TUNE_KEY_IS_PAYING_USER;

FOUNDATION_EXPORT NSString *const TUNE_KEY_PRELOAD_DATA;

FOUNDATION_EXPORT NSString *const TUNE_KEY_EXISTING_USER;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_EMAIL;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_EMAIL_MD5;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_EMAIL_SHA1;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_EMAIL_SHA256;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_NAME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_NAME_MD5;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_NAME_SHA1;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_NAME_SHA256;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_PHONE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_PHONE_MD5;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_PHONE_SHA1;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USER_PHONE_SHA256;
FOUNDATION_EXPORT NSString *const TUNE_KEY_FACEBOOK_USER_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_TWITTER_USER_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_GOOGLE_USER_ID;

FOUNDATION_EXPORT NSString *const TUNE_KEY_AGE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_GENDER;

FOUNDATION_EXPORT NSString *const TUNE_KEY_LATITUDE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_LONGITUDE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ALTITUDE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_LOCATION_HORIZONTAL_ACCURACY;
FOUNDATION_EXPORT NSString *const TUNE_KEY_LOCATION_TIMESTAMP;
FOUNDATION_EXPORT NSString *const TUNE_KEY_LOCATION_VERTICAL_ACCURACY;

FOUNDATION_EXPORT NSString *const TUNE_KEY_TRUSTE_TPID;

FOUNDATION_EXPORT NSString *const TUNE_KEY_OS_TYPE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_MODEL;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_CPUTYPE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_CPUSUBTYPE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_CARRIER;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_BRAND;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SCREEN_HEIGHT;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SCREEN_WIDTH;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SCREEN_SIZE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SCREEN_DENSITY;
FOUNDATION_EXPORT NSString *const TUNE_KEY_CARRIER_COUNTRY_CODE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_CARRIER_COUNTRY_CODE_ISO;
FOUNDATION_EXPORT NSString *const TUNE_KEY_CARRIER_NETWORK_CODE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_COUNTRY_CODE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_OS_VERSION;
FOUNDATION_EXPORT NSString *const TUNE_KEY_LANGUAGE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_LOCATION_AUTH_STATUS;
FOUNDATION_EXPORT NSString *const TUNE_KEY_BLUETOOTH_STATE;

//TODO: Add TUNE_KEY_SITE_EVENT_ID and TUNE_KEY_SITE_EVENT_NAME ?
FOUNDATION_EXPORT NSString *const TUNE_KEY_APP_BUNDLE_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_APP_NAME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_APP_VERSION;
FOUNDATION_EXPORT NSString *const TUNE_KEY_APP_VERSION_NAME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_KEY;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PACKAGE_NAME;

FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_FORM;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_FORM_TV;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_FORM_WEARABLE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_SUB_AD;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_SUB_ADGROUP;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_SUB_CAMPAIGN;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_SUB_KEYWORD;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_SUB_PUBLISHER;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ADVERTISER_SUB_SITE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_AGENCY_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_OFFER_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PRELOAD_DATA;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_REF_ID;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_AD;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_AD_REF;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_AD_NAME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_ADGROUP;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_CAMPAIGN;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_CAMPAIGN_REF;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_CAMPAIGN_NAME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_KEYWORD;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_KEYWORD_REF;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_PLACEMENT_REF;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_PLACEMENT_NAME;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_PUBLISHER;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_PUBLISHER_REF;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB_SITE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB1;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB2;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB3;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB4;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUBLISHER_SUB5;

FOUNDATION_EXPORT NSString *const TUNE_KEY_INTERFACE_IDIOM;
FOUNDATION_EXPORT NSString *const TUNE_KEY_HARDWARE_TYPE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_MINUTES_FROM_GMT;
FOUNDATION_EXPORT NSString *const TUNE_KEY_SDK_VERSION;
FOUNDATION_EXPORT NSString *const TUNE_KEY_DEVICE_TOKEN;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PUSH_ENABLED;

FOUNDATION_EXPORT NSString *const TUNE_KEY_GEO_COORDINATE;
FOUNDATION_EXPORT NSString *const TUNE_KEY_IS_TESTFLIGHT_BUILD;

@interface TuneUserProfileKeys : NSObject

+ (NSSet *)getSystemVariables;

@end
