//
//  TuneConfigurationKeys.h
//  TuneMarketingConsoleSDK
//
//  Created by Daniel Koch on 8/8/15.
//  Copyright (c) 2015 Tune. All rights reserved.
//

FOUNDATION_EXPORT NSString *const TUNE_KEY_DEBUG;
FOUNDATION_EXPORT NSString *const TUNE_KEY_STAGING;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ECHO_ANALYTICS;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ECHO_PLAYLISTS;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ECHO_CONFIGURATIONS;
FOUNDATION_EXPORT NSString *const TUNE_KEY_ECHO_FIVELINE;

FOUNDATION_EXPORT NSString *const TUNE_KEY_USE_PLAYLIST_PLAYER;
FOUNDATION_EXPORT NSString *const TUNE_KEY_PLAYLIST_PLAYER_FILENAMES;
FOUNDATION_EXPORT NSString *const TUNE_KEY_USE_CONFIGURATION_PLAYER;
FOUNDATION_EXPORT NSString *const TUNE_KEY_CONFIGURATION_PLAYER_FILENAMES;

FOUNDATION_EXPORT NSString *const TUNE_KEY_AUTO_IAP_MEASUREMENT;
FOUNDATION_EXPORT NSString *const TUNE_KEY_AUTOCOLLECT_JAILBROKEN;
FOUNDATION_EXPORT NSString *const TUNE_KEY_AUTOCOLLECT_LOCATION;
FOUNDATION_EXPORT NSString *const TUNE_KEY_AUTOCOLLECT_IFA;
FOUNDATION_EXPORT NSString *const TUNE_KEY_AUTOCOLLECT_IFV;

FOUNDATION_EXPORT NSString *const TUNE_TMA_PLAYLIST_HOST_PORT;
FOUNDATION_EXPORT NSString *const TUNE_TMA_CONFIGURATION_HOST_PORT;
FOUNDATION_EXPORT NSString *const TUNE_TMA_ANALYTICS_HOST_PORT;
FOUNDATION_EXPORT NSString *const TUNE_TMA_CONNECTED_MODE_HOST_PORT;
FOUNDATION_EXPORT NSString *const TUNE_TMA_STATIC_CONTENT_HOST_PORT;

FOUNDATION_EXPORT NSString *const TUNE_ANALYTICS_DISPATCH_PERIOD;
FOUNDATION_EXPORT NSString *const TUNE_ANALYTICS_MESSAGE_LIMIT;

FOUNDATION_EXPORT NSString *const TUNE_POLL_FOR_PLAYLIST;
FOUNDATION_EXPORT NSString *const TUNE_PLAYLIST_REQUEST_PERIOD;

FOUNDATION_EXPORT NSString *const TUNE_KEY_SDK_PLUGIN;

FOUNDATION_EXPORT NSString *const TUNE_DEBUG_LOGGING_ON;
FOUNDATION_EXPORT NSString *const TUNE_TMA_DISABLED;
FOUNDATION_EXPORT NSString *const TUNE_TMA_PERMANENTLY_DISABLED;

FOUNDATION_EXPORT NSString *const TUNE_TMA_CONNECTED_MODE;

FOUNDATION_EXPORT NSString *const TUNE_GLOBAL_SWIZZLE_OFF;
FOUNDATION_EXPORT NSString *const TUNE_SWIZZLE_BLACKLIST_ADDITIONS;
FOUNDATION_EXPORT NSString *const TUNE_SWIZZLE_BLACKLIST_REMOVALS;

FOUNDATION_EXPORT NSString *const TUNE_SEND_SCREEN_VIEWS;

FOUNDATION_EXPORT NSString *const TUNE_TMA_PII_FILTERS_NSSTRING;
