//
//  TuneAdView.h
//  Tune
//
//  Created by Harshal Ogale on 11/21/14.
//  Copyright (c) 2014 Tune Inc. All rights reserved.
//

#import <UIKit/UIKit.h>

@class TuneAd;

@protocol TuneAdDelegate;

/*!
 List of errors generated by TuneAdView.
 */
typedef NS_ENUM(NSInteger, TuneAdError)
{
    /*!
     Invalid placement value provided. Placement must be a string.
     */
    TuneAdErrorInvalidPlacement,
    /*!
     No ads are currently available because the SDK is unable to connect to the internet.
     */
    TuneAdErrorNetworkNotReachable,
    /*!
     The Ad server could not find any ads that matched the info provided.
     */
    TuneAdErrorNoMatchingAds,
    /*!
     The specified app/site/package name was not found on the server.
     */
    TuneAdErrorNoMatchingSites,
    /*!
     An unknown error occurred.
     */
    TuneAdErrorUnknown,
    /*!
     The specified advertiser id was not found on the server.
     */
    TuneAdErrorUnknownAdvertiser
};

/*!
 Types of ads
 */
typedef NS_ENUM(NSInteger, TuneAdType)
{
    TuneAdTypeBanner,
    TuneAdTypeInterstitial
};

/*!
 List of supported orientations
 */
typedef NS_OPTIONS(NSUInteger, TuneAdOrientation)
{
    TuneAdOrientationAll         = 0,
    TuneAdOrientationPortrait    = 1,
    TuneAdOrientationLandscape   = 1 << 1
};


/*!
 Tune ad view abstract class extended by TuneBanner and TuneInterstitial.
 To create an ad view instance, please directly use TuneBanner or TuneInterstitial as appropriate.
 */
@interface TuneAdView : UIView

/*!
 Delegate that handles callbacks from TuneAdView
 */
@property (nonatomic, assign) id<TuneAdDelegate> delegate;

/*!
 Allowed orientation(s) for this TuneAdView
 */
@property (nonatomic, assign, setter=setAllowedOrientations:) TuneAdOrientation adOrientations;

/*!
 Flag to check if the next ad is ready for display
 */
@property (nonatomic, getter=isReady, readonly) BOOL ready;

@end


/*!
 Protocol to be implemented in order to receive callbacks from this TuneAdView
 */
@protocol TuneAdDelegate <NSObject>

@required

/*!
 Required callback method called when the next ad is ready for display
 @param adView the current ad view object
 */
- (void)tuneAdDidFetchAdForView:(TuneAdView *)adView placement:(NSString *)placement;

@optional

/*!
 Optional callback method called when the user clicks the ad and an action is initiated.
 @param adView the ad view that the user tapped
 @param willLeave YES if another application will be launched to execute the action; NO if the action is going to be executed inside your application.
 */
- (void)tuneAdDidStartActionForView:(TuneAdView *)adView willLeaveApplication:(BOOL)willLeave;

/*!
 Optional callback method called when the user ad click action ends. This method is not called if tuneAdDidStartActionForView:willLeaveApplication: was called with willLeave = YES.
 @param adView the current ad view object
 */
- (void)tuneAdDidEndActionForView:(TuneAdView *)adView;

/*!
 Optional callback method called when the user clicks the close button on an interstitial ad. This method is not called for banner ads.
 @param adView the current ad view object
 */
- (void)tuneAdDidCloseForView:(TuneAdView *)adView;

/*!
 Optional callback method called when this ad view encounters an error.
 @param adView the current ad view object
 */
- (void)tuneAdDidFailWithError:(NSError *)error forView:(TuneAdView *)adView;

/*!
 Optional callback method called when a new ad fetch request is fired.
 @param adView the current ad view object
 */
- (void)tuneAdDidFireRequestWithUrl:(NSString *)url data:(NSString *)data forView:(TuneAdView *)adView;

@end
