//
//  TuneAnalyticsConstants.h
//  MobileAppTracker
//
//  Created by Charles Gilliam on 7/28/15.
//  Copyright (c) 2015 TUNE. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface TuneAnalyticsConstants : NSObject

FOUNDATION_EXPORT NSString *const TUNE_SCHEMA_VERSION;

#pragma mark - Event types
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_BASE;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_SESSION;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_PAGEVIEW;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_IN_APP_MESSAGE;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_PUSH_NOTIFICATION;

#pragma mark - URL-based events types
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_EMAIL;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_WEB;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_SMS;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_APP;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_AD;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_TODAY_EXTENSION;

#pragma mark - Event category values
FOUNDATION_EXPORT NSString *const TUNE_EVENT_CATEGORY_CUSTOM;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_CATEGORY_APPLICATION;

#pragma mark - Event Actions
// See TuneEvent.m for additional values.
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION_BACKGROUNDED;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION_FOREGROUNDED;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION_NOTIFICATION_OPENED;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION_DEEPLINK_OPENED;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION_FIRST_PLAYLIST_DOWNLOADED;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION_PROFILE_VARIABLES_CLEARED;

#pragma mark - Data Types
FOUNDATION_EXPORT NSString *const TUNE_DATA_TYPE_STRING;
FOUNDATION_EXPORT NSString *const TUNE_DATA_TYPE_DATETIME;
FOUNDATION_EXPORT NSString *const TUNE_DATA_TYPE_BOOLEAN;
FOUNDATION_EXPORT NSString *const TUNE_DATA_TYPE_FLOAT;
FOUNDATION_EXPORT NSString *const TUNE_DATA_TYPE_GEOLOCATION;
FOUNDATION_EXPORT NSString *const TUNE_DATA_TYPE_VERSION;

#pragma mark - Analytics Event 5 line names
FOUNDATION_EXPORT NSString *const TUNE_EVENT_CATEGORY;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_CONTROL_EVENT;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_CONTROL;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_ACTION;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_TYPE;
FOUNDATION_EXPORT NSString *const TUNE_EVENT_LOCATION;

#pragma mark - Category Analytics Variable Tags
FOUNDATION_EXPORT NSString *const TUNE_CATEGORY_PARAMETER;
FOUNDATION_EXPORT NSString *const TUNE_SUB_CATEGORY_PARAMETER;
FOUNDATION_EXPORT NSString *const TUNE_SUB_SUB_CATEGORY_PARAMETER;

#pragma mark - Campaign IDs
FOUNDATION_EXPORT NSString *const TUNE_CAMPAIGN_IDENTIFIER;
FOUNDATION_EXPORT NSString *const TUNE_ANALYTICS_CAMPAIGN_IDENTIFIER;
FOUNDATION_EXPORT NSString *const TUNE_CAMPAIGN_STEP_IDENTIFIER;
FOUNDATION_EXPORT NSString *const TUNE_CAMPAIGN_VARIATION_IDENTIFIER;

#pragma mark - Current Variations
FOUNDATION_EXPORT NSString *const TUNE_ACTIVE_VARIATION_ID;

#pragma mark - For recording in app messages
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_IDENTIFIER;
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_ACTION_SHOWN;
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_ACTION_DISMISSED_AFTER_DURATION;
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_SECONDS_DISPLAYED;
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_ACTION_CANCEL_BUTTON_PRESSED;
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_ACTION_CLOSE_BUTTON_PRESSED;
FOUNDATION_EXPORT NSString *const TUNE_IN_APP_MESSAGE_UNSPECIFIED_ACTION_NAME;

#pragma mark - Hash Types
FOUNDATION_EXPORT NSString *const TUNE_HASH_TYPE_NONE;
FOUNDATION_EXPORT NSString *const TUNE_HASH_TYPE_MD5;
FOUNDATION_EXPORT NSString *const TUNE_HASH_TYPE_SHA1;
FOUNDATION_EXPORT NSString *const TUNE_HASH_TYPE_SHA256;

#pragma mark - Push Notifications
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ID;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ACTION;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ACTION_IGNORED;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ACTION_IGNORED_OPEN_URL;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ACTION_IGNORED_DEEP_ACTION;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ACTION_OPEN_URL;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_ACTION_DEEP_ACTION;
FOUNDATION_EXPORT NSString *const TUNE_PUSH_NOTIFICATION_NO_ACTION;
FOUNDATION_EXPORT NSString *const TUNE_INTERACTIVE_NOTIFICATION_BUTTON_IDENTIFIER_SELECTED;
FOUNDATION_EXPORT NSString *const TUNE_INTERACTIVE_NOTIFICATION_CATEGORY;

@end
