//
//  TuneAnalyticsConstants.m
//  MobileAppTracker
//
//  Created by Charles Gilliam on 7/28/15.
//  Copyright (c) 2015 TUNE. All rights reserved.
//

#import "TuneAnalyticsConstants.h"

@implementation TuneAnalyticsConstants

NSString *const TUNE_SCHEMA_VERSION = @"2.0";

#pragma mark - Event types
NSString *const TUNE_EVENT_TYPE_BASE = @"EVENT";
NSString *const TUNE_EVENT_TYPE_SESSION = @"SESSION";
NSString *const TUNE_EVENT_TYPE_PAGEVIEW = @"PAGEVIEW";
NSString *const TUNE_EVENT_TYPE_IN_APP_MESSAGE = @"IN_APP_MESSAGE";
NSString *const TUNE_EVENT_TYPE_PUSH_NOTIFICATION = @"PUSH_NOTIFICATION";

#pragma mark - URL-based events types
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL = @"APP_OPENED_BY_URL";
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_EMAIL = @"APP_OPENED_BY_URL_FROM_EMAIL";
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_WEB = @"APP_OPENED_BY_URL_FROM_WEB";
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_SMS = @"APP_OPENED_BY_URL_FROM_SMS";
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_APP = @"APP_OPENED_BY_URL_FROM_APP";
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_AD = @"APP_OPENED_BY_URL_FROM_AD";
NSString *const TUNE_EVENT_TYPE_APP_OPENED_BY_URL_FROM_TODAY_EXTENSION = @"APP_OPENED_BY_URL_FROM_TODAY_EXTENSION";

#pragma mark - Event category values
NSString *const TUNE_EVENT_CATEGORY_CUSTOM = @"Custom";
NSString *const TUNE_EVENT_CATEGORY_APPLICATION = @"Application";

#pragma mark - Event Actions
// See TuneEvent.m for current list.
NSString *const TUNE_EVENT_ACTION_BACKGROUNDED = @"Backgrounded";
NSString *const TUNE_EVENT_ACTION_FOREGROUNDED = @"Foregrounded";
NSString *const TUNE_EVENT_ACTION_NOTIFICATION_OPENED = @"NotificationOpened";
NSString *const TUNE_EVENT_ACTION_DEEPLINK_OPENED = @"DeeplinkOpened";
NSString *const TUNE_EVENT_ACTION_FIRST_PLAYLIST_DOWNLOADED = @"FirstPlaylistDownloaded";
NSString *const TUNE_EVENT_ACTION_PROFILE_VARIABLES_CLEARED = @"ClearVariables";

#pragma mark - Data Types
NSString *const TUNE_DATA_TYPE_STRING = @"string";
NSString *const TUNE_DATA_TYPE_DATETIME = @"datetime";
NSString *const TUNE_DATA_TYPE_BOOLEAN = @"boolean";
NSString *const TUNE_DATA_TYPE_FLOAT = @"float";
NSString *const TUNE_DATA_TYPE_GEOLOCATION = @"geolocation";
NSString *const TUNE_DATA_TYPE_VERSION = @"version";

#pragma mark - Analytics Event 5 line names
NSString *const TUNE_EVENT_CATEGORY = @"category";
NSString *const TUNE_EVENT_CONTROL_EVENT = @"controlEvent";
NSString *const TUNE_EVENT_CONTROL = @"control";
NSString *const TUNE_EVENT_ACTION = @"action";
NSString *const TUNE_EVENT_TYPE = @"type";
NSString *const TUNE_EVENT_LOCATION = @"location";

#pragma mark - Category Analytics Variable Tags
NSString *const TUNE_CATEGORY_PARAMETER = @"category";
NSString *const TUNE_SUB_CATEGORY_PARAMETER = @"subCategory";
NSString *const TUNE_SUB_SUB_CATEGORY_PARAMETER = @"subSubCategory";

#pragma mark - Campaign IDs
NSString *const TUNE_CAMPAIGN_IDENTIFIER = @"CAMPAIGN_ID";
NSString *const TUNE_ANALYTICS_CAMPAIGN_IDENTIFIER = @"TUNE_CAMPAIGN_ID";
NSString *const TUNE_CAMPAIGN_STEP_IDENTIFIER = @"TUNE_CAMPAIGN_STEP_ID";
NSString *const TUNE_CAMPAIGN_VARIATION_IDENTIFIER = @"TUNE_CAMPAIGN_VARIATION_ID";

#pragma mark - Current Variations
NSString *const TUNE_ACTIVE_VARIATION_ID = @"TUNE_ACTIVE_VARIATION_ID";

#pragma mark - For recording in app messages
NSString *const TUNE_IN_APP_MESSAGE_IDENTIFIER = @"TUNE_IN_APP_MESSAGE_ID";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_SHOWN = @"TUNE_IN_APP_MESSAGE_ACTION_SHOWN";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_DISMISSED_AFTER_DURATION = @"TUNE_IN_APP_MESSAGE_ACTION_DISMISSED_AFTER_DURATION";
NSString *const TUNE_IN_APP_MESSAGE_SECONDS_DISPLAYED = @"TUNE_IN_APP_MESSAGE_SECONDS_DISPLAYED";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_CTA_BUTTON_PRESSED = @"TUNE_IN_APP_MESSAGE_ACTION_CTA_BUTTON_PRESSED";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_CANCEL_BUTTON_PRESSED = @"TUNE_IN_APP_MESSAGE_ACTION_CANCEL_BUTTON_PRESSED";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_CLOSE_BUTTON_PRESSED = @"TUNE_IN_APP_MESSAGE_ACTION_CLOSE_BUTTON_PRESSED";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_CONTENT_AREA_PRESSED = @"TUNE_IN_APP_MESSAGE_ACTION_CONTENT_AREA_PRESSED";
NSString *const TUNE_IN_APP_MESSAGE_ACTION_MESSAGE_PRESSED = @"TUNE_IN_APP_MESSAGE_ACTION_MESSAGE_PRESSED";

#pragma mark - Hash Types
NSString *const TUNE_HASH_TYPE_NONE = @"none";
NSString *const TUNE_HASH_TYPE_MD5 = @"md5";
NSString *const TUNE_HASH_TYPE_SHA1 = @"sha1";
NSString *const TUNE_HASH_TYPE_SHA256 = @"sha256";

#pragma mark - Push Notifications
NSString *const TUNE_PUSH_NOTIFICATION_ID = @"ARTPID";
NSString *const TUNE_PUSH_NOTIFICATION_ACTION = @"TUNE_PUSH_NOTIFICATION_ACTION";
NSString *const TUNE_PUSH_NOTIFICATION_ACTION_IGNORED = @"INAPP_IGNORED";
NSString *const TUNE_PUSH_NOTIFICATION_ACTION_IGNORED_OPEN_URL = @"INAPP_IGNORED_OPEN_URL";
NSString *const TUNE_PUSH_NOTIFICATION_ACTION_IGNORED_DEEP_ACTION = @"INAPP_IGNORED_DEEP_ACTION";
NSString *const TUNE_PUSH_NOTIFICATION_ACTION_OPEN_URL = @"INAPP_OPEN_URL";
NSString *const TUNE_PUSH_NOTIFICATION_ACTION_DEEP_ACTION = @"INAPP_DEEP_ACTION";
NSString *const TUNE_PUSH_NOTIFICATION_NO_ACTION = @"INAPP_NO_ACTION";
NSString *const TUNE_INTERACTIVE_NOTIFICATION_BUTTON_IDENTIFIER_SELECTED = @"NOTIFICATION_IDENTIFIER_SELECTED";
NSString *const TUNE_INTERACTIVE_NOTIFICATION_CATEGORY = @"NOTIFICATION_CATEGORY";

@end
