//
//  TuneAdKeyStrings.h
//  Tune
//
//  Created by Harshal Ogale on 8/15/14.
//  Copyright (c) 2014 Tune. All rights reserved.
//

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdErrorDomain;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdErrorUnknown;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdErrorNetworkNotReachable;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdErrorInvalidPlacement;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdServerErrorNoMatchingAdGroups;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdServerErrorNoMatchingPlacement;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdServerErrorNoMatchingSites;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdServerErrorNoSpecifiedSizes;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdServerErrorNoSuitableAds;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_TuneAdServerErrorUnknownAdvertiser;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_NATIVE;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_HTML;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_DURATION;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_REFS;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_REQUEST_ID;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_COLOR;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_ERROR;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_CLICK;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_CLOSE;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_EVENT;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_VIEW;

FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_ACTION;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SITE_ID;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_PUBLISHER;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_CAMPAIGN;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_AD;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_AD_GROUP;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_SITE;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_1;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_2;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_3;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_4;
FOUNDATION_EXPORT NSString * const TUNE_AD_KEY_SUB_5;

FOUNDATION_EXPORT NSString * const TUNE_HTTP_METHOD_GET;
