//
//  MATKeyStrings.h
//  MobileAppTrackeriOS
//
//  Created by Pavel Yurchenko on 7/16/12.
//  Copyright (c) 2012 Scopic Software. All rights reserved.
//

FOUNDATION_EXPORT NSString * const MAT_KEY_ACTION;
FOUNDATION_EXPORT NSString * const MAT_KEY_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_APP_AD_TRACKING;
FOUNDATION_EXPORT NSString * const MAT_KEY_APP_NAME;
FOUNDATION_EXPORT NSString * const MAT_KEY_APP_VERSION;
FOUNDATION_EXPORT NSString * const MAT_KEY_BYPASS_THROTTLING;
FOUNDATION_EXPORT NSString * const MAT_KEY_CAMPAIGN_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_CONVERSION_USER_AGENT;
FOUNDATION_EXPORT NSString * const MAT_KEY_COUNTRY_CODE;
FOUNDATION_EXPORT NSString * const MAT_KEY_CURRENCY_CODE;
FOUNDATION_EXPORT NSString * const MAT_KEY_CURRENCY_USD;
FOUNDATION_EXPORT NSString * const MAT_KEY_DATA;
FOUNDATION_EXPORT NSString * const MAT_KEY_DEBUG;
FOUNDATION_EXPORT NSString * const MAT_KEY_DEVICE_BRAND;
FOUNDATION_EXPORT NSString * const MAT_KEY_DEVICE_CARRIER;
FOUNDATION_EXPORT NSString * const MAT_KEY_DEVICE_CPUTYPE;
FOUNDATION_EXPORT NSString * const MAT_KEY_DEVICE_CPUSUBTYPE;
FOUNDATION_EXPORT NSString * const MAT_KEY_DEVICE_MODEL;
FOUNDATION_EXPORT NSString * const MAT_KEY_EXISTING_USER;
FOUNDATION_EXPORT NSString * const MAT_KEY_FACEBOOK_USER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_FB_COOKIE_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_GEOFENCE_NAME;
FOUNDATION_EXPORT NSString * const MAT_KEY_GOOGLE_USER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_GUID_EMPTY;
FOUNDATION_EXPORT NSString * const MAT_KEY_HTTPS;
FOUNDATION_EXPORT NSString * const MAT_KEY_INSDATE;
FOUNDATION_EXPORT NSString * const MAT_KEY_IAD_ATTRIBUTION;
FOUNDATION_EXPORT NSString * const MAT_KEY_IAD_IMPRESSION_DATE;
FOUNDATION_EXPORT NSString * const MAT_KEY_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_INSTALL_RECEIPT;
FOUNDATION_EXPORT NSString * const MAT_KEY_IOS;
FOUNDATION_EXPORT NSString * const MAT_KEY_IOS_AD_TRACKING;
FOUNDATION_EXPORT NSString * const MAT_KEY_IOS_IFA;
FOUNDATION_EXPORT NSString * const MAT_KEY_IOS_IFV;
FOUNDATION_EXPORT NSString * const MAT_KEY_IOS_PURCHASE_STATUS;
FOUNDATION_EXPORT NSString * const MAT_KEY_IS_PAYING_USER;
FOUNDATION_EXPORT NSString * const MAT_KEY_JSON;
FOUNDATION_EXPORT NSString * const MAT_KEY_KEY;
FOUNDATION_EXPORT NSString * const MAT_KEY_LAST_OPEN_LOG_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_LANGUAGE;
FOUNDATION_EXPORT NSString * const MAT_KEY_LOCATION_AUTH_STATUS;
FOUNDATION_EXPORT NSString * const MAT_KEY_LOG_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_MAT_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_ODIN;
FOUNDATION_EXPORT NSString * const MAT_KEY_OPEN_LOG_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_OPEN_UDID;
FOUNDATION_EXPORT NSString * const MAT_KEY_OS_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_OS_JAILBROKE;
FOUNDATION_EXPORT NSString * const MAT_KEY_OS_VERSION;
FOUNDATION_EXPORT NSString * const MAT_KEY_PACKAGE_NAME;
FOUNDATION_EXPORT NSString * const MAT_KEY_POST_CONVERSION;
FOUNDATION_EXPORT NSString * const MAT_KEY_PUBLISHER_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_PUBLISHER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_REDIRECT;
FOUNDATION_EXPORT NSString * const MAT_KEY_REDIRECT_URL;
FOUNDATION_EXPORT NSString * const MAT_KEY_REF_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_REFERRAL_SOURCE;
FOUNDATION_EXPORT NSString * const MAT_KEY_REFERRAL_URL;
FOUNDATION_EXPORT NSString * const MAT_KEY_RESPONSE_FORMAT;
FOUNDATION_EXPORT NSString * const MAT_KEY_REVENUE;
FOUNDATION_EXPORT NSString * const MAT_KEY_RETRY_COUNT;
FOUNDATION_EXPORT NSString * const MAT_KEY_RUN_DATE;
FOUNDATION_EXPORT NSString * const MAT_KEY_SCREEN_DENSITY;
FOUNDATION_EXPORT NSString * const MAT_KEY_SCREEN_SIZE;
FOUNDATION_EXPORT NSString * const MAT_KEY_SDK;
FOUNDATION_EXPORT NSString * const MAT_KEY_SDK_PLUGIN;
FOUNDATION_EXPORT NSString * const MAT_KEY_SERVER_RESPONSE;
FOUNDATION_EXPORT NSString * const MAT_KEY_SESSION_DATETIME;
FOUNDATION_EXPORT NSString * const MAT_KEY_SITE_EVENT_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_SITE_EVENT_NAME;
FOUNDATION_EXPORT NSString * const MAT_KEY_SITE_EVENT_TYPE;
FOUNDATION_EXPORT NSString * const MAT_KEY_SKIP_DUP;
FOUNDATION_EXPORT NSString * const MAT_KEY_SITE_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_STAGING;
FOUNDATION_EXPORT NSString * const MAT_KEY_STORE_RECEIPT;
FOUNDATION_EXPORT NSString * const MAT_KEY_SUCCESS;
FOUNDATION_EXPORT NSString * const MAT_KEY_SYSTEM_DATE;
FOUNDATION_EXPORT NSString * const MAT_KEY_TARGET_BUNDLE_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_TRACKING_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_TRANSACTION_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_TRUSTE_TPID;
FOUNDATION_EXPORT NSString * const MAT_KEY_TWITTER_USER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_UPDATE_LOG_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_URL;
FOUNDATION_EXPORT NSString * const MAT_KEY_USER_EMAIL;
FOUNDATION_EXPORT NSString * const MAT_KEY_USER_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_USER_NAME;
FOUNDATION_EXPORT NSString * const MAT_KEY_VER;
FOUNDATION_EXPORT NSString * const MAT_KEY_XML;

FOUNDATION_EXPORT NSString * const MAT_KEY_CWORKS_CLICK;
FOUNDATION_EXPORT NSString * const MAT_KEY_CWORKS_IMPRESSION;

FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_CONTENT_TYPE;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_CONTENT_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_LEVEL;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_QUANTITY;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_SEARCH_STRING;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_RATING;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_DATE1;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_DATE2;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_ATTRIBUTE_SUB1;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_ATTRIBUTE_SUB2;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_ATTRIBUTE_SUB3;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_ATTRIBUTE_SUB4;
FOUNDATION_EXPORT NSString * const MAT_KEY_EVENT_ATTRIBUTE_SUB5;

FOUNDATION_EXPORT NSString * const MAT_KEY_ITEM;
FOUNDATION_EXPORT NSString * const MAT_KEY_QUANTITY;
FOUNDATION_EXPORT NSString * const MAT_KEY_UNIT_PRICE;

FOUNDATION_EXPORT NSString * const MAT_KEY_AGE;
FOUNDATION_EXPORT NSString * const MAT_KEY_GENDER;

FOUNDATION_EXPORT NSString * const MAT_KEY_LATITUDE;
FOUNDATION_EXPORT NSString * const MAT_KEY_LONGITUDE;
FOUNDATION_EXPORT NSString * const MAT_KEY_ALTITUDE;

FOUNDATION_EXPORT NSString * const MAT_KEY_ATTRIBUTE_SUB1;
FOUNDATION_EXPORT NSString * const MAT_KEY_ATTRIBUTE_SUB2;
FOUNDATION_EXPORT NSString * const MAT_KEY_ATTRIBUTE_SUB3;
FOUNDATION_EXPORT NSString * const MAT_KEY_ATTRIBUTE_SUB4;
FOUNDATION_EXPORT NSString * const MAT_KEY_ATTRIBUTE_SUB5;

FOUNDATION_EXPORT NSString * const MAT_KEY_CARRIER_COUNTRY_CODE;
FOUNDATION_EXPORT NSString * const MAT_KEY_CARRIER_COUNTRY_CODE_ISO;
FOUNDATION_EXPORT NSString * const MAT_KEY_CARRIER_NETWORK_CODE;

FOUNDATION_EXPORT NSString * const MAT_DEFAULT_LOCALE_IDENTIFIER;
FOUNDATION_EXPORT NSString * const MAT_DEFAULT_TIMEZONE;

FOUNDATION_EXPORT NSString * const MAT_EVENT_INSTALL;
FOUNDATION_EXPORT NSString * const MAT_EVENT_UPDATE;
FOUNDATION_EXPORT NSString * const MAT_EVENT_OPEN;
FOUNDATION_EXPORT NSString * const MAT_EVENT_CLICK;
FOUNDATION_EXPORT NSString * const MAT_EVENT_CLOSE;
FOUNDATION_EXPORT NSString * const MAT_EVENT_CONVERSION;
FOUNDATION_EXPORT NSString * const MAT_EVENT_SESSION;
FOUNDATION_EXPORT NSString * const MAT_EVENT_GEOFENCE;

FOUNDATION_EXPORT NSString * const MAT_HTTP_METHOD_POST;
FOUNDATION_EXPORT NSString * const MAT_HTTP_CONTENT_LENGTH;
FOUNDATION_EXPORT NSString * const MAT_HTTP_CONTENT_TYPE;
FOUNDATION_EXPORT NSString * const MAT_HTTP_CONTENT_TYPE_APPLICATION_JSON;

FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_DOMAIN_MOBILEAPPTRACKER;

FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_SERVER_ERROR;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_ADVERTISER_ID_MISSING;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_CONVERSION_KEY_MISSING;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_CONVERSION_KEY_INVALID;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_INVALID_PARAMETERS;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_APP_TO_APP_FAILURE;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_NETWORK_NOT_REACHABLE;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_OPEN_EVENT;
FOUNDATION_EXPORT NSString * const MAT_KEY_ERROR_MAT_CLOSE_EVENT;

FOUNDATION_EXPORT NSString * const MAT_KEY_MAT_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString * const MAT_KEY_MAT_INSTALL_LOG_ID_REQUEST_TIMESTAMP;
FOUNDATION_EXPORT NSString * const MAT_KEY_MAT_UPDATE_LOG_ID;

FOUNDATION_EXPORT NSString * const MAT_KEY_MAT_FIXED_FOR_ICLOUD;

FOUNDATION_EXPORT NSString * const MAT_STRING_EMPTY;

FOUNDATION_EXPORT NSString * const MAT_SERVER_DOMAIN_COOKIE_TRACKING;
FOUNDATION_EXPORT NSString * const MAT_SERVER_DOMAIN_REGULAR_TRACKING_PROD;
FOUNDATION_EXPORT NSString * const MAT_SERVER_DOMAIN_REGULAR_TRACKING_PROD_DEBUG;
FOUNDATION_EXPORT NSString * const MAT_SERVER_DOMAIN_REGULAR_TRACKING_STAGE;
FOUNDATION_EXPORT NSString * const MAT_SERVER_PATH_TRACKING_ENGINE;
