//
//  MATKeyStrings.h
//  MobileAppTrackeriOS
//
//  Created by Pavel Yurchenko on 7/16/12.
//  Copyright (c) 2012 Scopic Software. All rights reserved.
//

FOUNDATION_EXPORT NSString * const KEY_ACTION;
FOUNDATION_EXPORT NSString * const KEY_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const KEY_APP_NAME;
FOUNDATION_EXPORT NSString * const KEY_APP_VERSION;
FOUNDATION_EXPORT NSString * const KEY_APPLE;
FOUNDATION_EXPORT NSString * const KEY_CAMPAIGN_ID;
FOUNDATION_EXPORT NSString * const KEY_CFBUNDLEIDENTIFIER;
FOUNDATION_EXPORT NSString * const KEY_CFBUNDLENAME;
FOUNDATION_EXPORT NSString * const KEY_CFBUNDLEVERSION;
FOUNDATION_EXPORT NSString * const KEY_CONVERSION_USER_AGENT;
FOUNDATION_EXPORT NSString * const KEY_COUNTRY_CODE;
FOUNDATION_EXPORT NSString * const KEY_CURRENCY;
FOUNDATION_EXPORT NSString * const KEY_CURRENCY_USD;
FOUNDATION_EXPORT NSString * const KEY_DATA;
FOUNDATION_EXPORT NSString * const KEY_DEBUG;
FOUNDATION_EXPORT NSString * const KEY_DEVICE_BRAND;
FOUNDATION_EXPORT NSString * const KEY_DEVICE_CARRIER;
FOUNDATION_EXPORT NSString * const KEY_DEVICE_MODEL;
FOUNDATION_EXPORT NSString * const KEY_DOMAIN;
FOUNDATION_EXPORT NSString * const KEY_EVENT_REFERRAL;
FOUNDATION_EXPORT NSString * const KEY_FB_COOKIE_ID;
FOUNDATION_EXPORT NSString * const KEY_GUID_EMPTY;
FOUNDATION_EXPORT NSString * const KEY_HTTP;
FOUNDATION_EXPORT NSString * const KEY_HTTPS;
FOUNDATION_EXPORT NSString * const KEY_INSDATE;
FOUNDATION_EXPORT NSString * const KEY_INSTALL_DATE;
FOUNDATION_EXPORT NSString * const KEY_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString * const KEY_IOS;
FOUNDATION_EXPORT NSString * const KEY_IOS_AD_TRACKING;
FOUNDATION_EXPORT NSString * const KEY_IOS_IFA;
FOUNDATION_EXPORT NSString * const KEY_IOS_IFV;
FOUNDATION_EXPORT NSString * const KEY_IOS_PURCHASE_STATUS;
FOUNDATION_EXPORT NSString * const KEY_JSON;
FOUNDATION_EXPORT NSString * const KEY_KEY;
FOUNDATION_EXPORT NSString * const KEY_KEY_INDEX;
FOUNDATION_EXPORT NSString * const KEY_LANGUAGE;
FOUNDATION_EXPORT NSString * const KEY_MAC_ADDRESS;
FOUNDATION_EXPORT NSString * const KEY_MAT_APP_VERSION;
FOUNDATION_EXPORT NSString * const KEY_MAT_ID;
FOUNDATION_EXPORT NSString * const KEY_ODIN;
FOUNDATION_EXPORT NSString * const KEY_OPEN_UDID;
FOUNDATION_EXPORT NSString * const KEY_OS_JAILBROKE;
FOUNDATION_EXPORT NSString * const KEY_OS_VERSION;
FOUNDATION_EXPORT NSString * const KEY_PACKAGE_NAME;
FOUNDATION_EXPORT NSString * const KEY_PUBLISHER_ADVERTISER_ID;
FOUNDATION_EXPORT NSString * const KEY_PUBLISHER_ID;
FOUNDATION_EXPORT NSString * const KEY_REDIRECT;
FOUNDATION_EXPORT NSString * const KEY_REDIRECT_URL;
FOUNDATION_EXPORT NSString * const KEY_REF_ID;
FOUNDATION_EXPORT NSString * const KEY_RESPONSE_FORMAT;
FOUNDATION_EXPORT NSString * const KEY_REVENUE;
FOUNDATION_EXPORT NSString * const KEY_SDK;
FOUNDATION_EXPORT NSString * const KEY_SERVER_RESPONSE;
FOUNDATION_EXPORT NSString * const KEY_SESSION_DATETIME;
FOUNDATION_EXPORT NSString * const KEY_SITE_EVENT_ID;
FOUNDATION_EXPORT NSString * const KEY_SITE_EVENT_NAME;
FOUNDATION_EXPORT NSString * const KEY_SKIP_DUP;
FOUNDATION_EXPORT NSString * const KEY_SITE_ID;
FOUNDATION_EXPORT NSString * const KEY_SOURCE;
FOUNDATION_EXPORT NSString * const KEY_STAGING;
FOUNDATION_EXPORT NSString * const KEY_SUCCESS;
FOUNDATION_EXPORT NSString * const KEY_SYSTEM_DATE;
FOUNDATION_EXPORT NSString * const KEY_TARGET_BUNDLE_ID;
FOUNDATION_EXPORT NSString * const KEY_TRACKING_ID;
FOUNDATION_EXPORT NSString * const KEY_TRUSTE_TPID;
FOUNDATION_EXPORT NSString * const KEY_UPDATE_LOG_ID;
FOUNDATION_EXPORT NSString * const KEY_URL;
FOUNDATION_EXPORT NSString * const KEY_USER_ID;
FOUNDATION_EXPORT NSString * const KEY_VER;
FOUNDATION_EXPORT NSString * const KEY_XML;

FOUNDATION_EXPORT NSString * const KEY_CARRIER_COUNTRY_CODE;
FOUNDATION_EXPORT NSString * const KEY_CARRIER_COUNTRY_CODE_ISO;
FOUNDATION_EXPORT NSString * const KEY_CARRIER_NETWORK_CODE;

FOUNDATION_EXPORT NSString * const DEFAULT_LOCALE_IDENTIFIER;
FOUNDATION_EXPORT NSString * const DEFAULT_TIMEZONE;

FOUNDATION_EXPORT NSString * const NORMALLY_ENCRYPTED;
FOUNDATION_EXPORT NSString * const HIGHLY_ENCRYPTED;

FOUNDATION_EXPORT NSString * const EVENT_INSTALL;
FOUNDATION_EXPORT NSString * const EVENT_UPDATE;
FOUNDATION_EXPORT NSString * const EVENT_OPEN;
FOUNDATION_EXPORT NSString * const EVENT_CLICK;
FOUNDATION_EXPORT NSString * const EVENT_CLOSE;
FOUNDATION_EXPORT NSString * const EVENT_CONVERSION;

FOUNDATION_EXPORT NSString * const HTTP_METHOD_POST;
FOUNDATION_EXPORT NSString * const HTTP_CONTENT_TYPE;
FOUNDATION_EXPORT NSString * const HTTP_CONTENT_TYPE_APPLICATION_JSON;

FOUNDATION_EXPORT NSString * const KEY_ERROR_DOMAIN_MOBILEAPPTRACKER;

FOUNDATION_EXPORT NSString * const KEY_ERROR_MAT_SERVER_ERROR;
FOUNDATION_EXPORT NSString * const KEY_ERROR_MAT_ADVERTISER_ID_MISSING;
FOUNDATION_EXPORT NSString * const KEY_ERROR_MAT_CONVERSION_KEY_MISSING;
FOUNDATION_EXPORT NSString * const KEY_ERROR_MAT_APP_TO_APP_FAILURE;
FOUNDATION_EXPORT NSString * const KEY_ERROR_MAT_NETWORK_NOT_REACHABLE;
FOUNDATION_EXPORT NSString * const KEY_ERROR_MAT_OPEN_EVENT_ERROR;

FOUNDATION_EXPORT NSString * const KEY_MAT_INSTALL_LOG_ID;
FOUNDATION_EXPORT NSString * const KEY_MAT_INSTALL_LOG_ID_REQUEST_TIMESTAMP;
FOUNDATION_EXPORT NSString * const KEY_MAT_OPEN_EVENT_TIMESTAMP;
FOUNDATION_EXPORT NSString * const KEY_MAT_UPDATE_LOG_ID;

FOUNDATION_EXPORT NSString * const KEY_MAT_FIXED_FOR_ICLOUD;

FOUNDATION_EXPORT NSString * const STRING_EMPTY;

FOUNDATION_EXPORT NSString * const SERVER_DOMAIN_COOKIE_TRACKING;
FOUNDATION_EXPORT NSString * const SERVER_DOMAIN_REGULAR_TRACKING_PROD;
FOUNDATION_EXPORT NSString * const SERVER_DOMAIN_REGULAR_TRACKING_PROD_DEBUG;
FOUNDATION_EXPORT NSString * const SERVER_DOMAIN_REGULAR_TRACKING_STAGE;
FOUNDATION_EXPORT NSString * const SERVER_PATH_TRACKING_ENGINE;
FOUNDATION_EXPORT NSString * const SERVER_PATH_TRACKING_ENGINE_NO_LOG;
FOUNDATION_EXPORT NSString * const SERVER_PATH_GET_INSTALL_LOG_ID;
